CREATE DATABASE ONOFRE_STORE;

CREATE SEQUENCE SQ_CUSTOMER START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_CUSTOMER(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
CUSTOMER_NAME VARCHAR(100) NOT NULL,
CUSTOMER_AGE VARCHAR(3) NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
PRIMARY KEY(ID)
);

CREATE SEQUENCE SQ_ORDER START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_ORDER(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
STATUS VARCHAR(20) NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
TOTAL BIGINT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES TBL_CUSTOMER(ID)
);

CREATE SEQUENCE SQ_PRODUCT START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_PRODUCT(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
PRODUCT_NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(3) NOT NULL,
UNIT_VALUE BIGINT NOT NULLL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
PRIMARY KEY(ID)
);

CREATE SEQUENCE SQ_ORDER_ITEM START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_ORDER_ITEM(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
AMOUNT BIGINT NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(ORDER_ID) REFERENCES TBL_ORDER(ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES TBL_PRODUCT(ID)
);

CREATE SEQUENCE SQ_USER START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_USER(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
LOGIN VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(16) NOT NULL,
ROLE VARCHAR(30) NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
PRIMARY KEY(ID)
);

CREATE SEQUENCE SQ_EMPLOYEE START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_EMPLOYEE(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
CPF VARCHAR(15) NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
ALT_DATE TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(USER_ID) REFERENCES TBL_USER(ID)
);